name: "my_perform_app"
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  url_launcher: ^6.1.10
  flutter_web_browser: ^0.17.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
  - assets/bdd.txt
  - assets/images/logoMyPerform.png
  uses-material-design: true
